export enum AppView {
  ONBOARDING = 'ONBOARDING',
  DASHBOARD = 'DASHBOARD',
  CLASH = 'CLASH',
  STEAL = 'STEAL',
  PROFILE = 'PROFILE',
  TROPHY = 'TROPHY',
  CAMERA = 'CAMERA',
  ADD_FRIEND = 'ADD_FRIEND'
}

export enum RelationshipLevel {
  CIVILIAN = 1, // Wholesome
  ROAST = 2,    // Embarrassing
  NUCLEAR = 3   // Deep/Vulgar
}

export interface UserProfile {
  id: string;
  name: string;
  age: string;
  gender: string;
  coins: number;
  riskProfile: string; // Generated by AI
  avatarUrl: string;
  socialDebt: number;
}

export interface BetScenario {
  id: string;
  text: string;
  backgroundType: 'bedroom' | 'gym' | 'club' | 'street' | 'office';
  opponentName: string;
  stake: number;
  category: string;
  friendVote: boolean; // True = Yes, False = No (Hidden until user swipes)
}

export interface ActiveBet {
  id: string;
  scenario: string;
  opponentName: string;
  stake: number;
  status: 'pending_proof' | 'reviewing' | 'completed';
  proofUrl?: string;
  expiryTime?: number;
}

export interface Friend {
  id: string;
  name: string;
  relationshipLevel: RelationshipLevel;
  status: 'online' | 'offline';
  friendshipStatus: 'accepted' | 'pending_sent' | 'pending_received';
  coins: number;
  avatarUrl: string;
}

export interface ChatMessage {
  sender: 'ai' | 'user';
  text: string;
}